### ISSUE TITLE
202018010308_Emma_MV_Exercise

### ISSUE THREAD

**Issue by EmmaYuan123** [happymondaynkanta/Machine-Vision-Module#3]
Here is my work
[Week3_Loss_function_and_Optimization_Blank-checkpoint.zip](https://github.com/happymondaynkanta/Machine-Vision-Module/files/13110162/Week3_Loss_function_and_Optimization_Blank-checkpoint.zip)

**Comment by happymondaynkanta** [comment]
I could not view your assignment

**Comment by EmmaYuan123** [comment]
Sorry I will reopen it
